name: "Stream Deck Package"
description: "Package your Stream Deck plugin using the Elgato Maker CLI"
author: "j4ckofalltrades"
branding:
  icon: package
  color: blue
inputs:
  input-directory:
    description: "Path of the plugin to pack (the *.sdPlugin directory)"
    required: true
  output-directory:
    description: "Specifies the path for the output directory where the .streamDeckPlugin file will be created"
    required: false
    default: 'release'
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Package the Stream Deck plugin
      shell: bash
      run: |
        npm install -g @elgato/cli@0.3.0
        streamdeck validate '${{ inputs.input-directory }}' --no-update-check
        streamdeck pack '${{ inputs.input-directory }}' --output '${{ inputs.output-directory }}' --no-update-check
    - name: Upload the plugin artifact
      uses: actions/upload-artifact@v4
      with:
        name: streamdeck-plugin
        path: ${{ inputs.output-directory }}
    - name: Create GitHub Release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release create '${{ github.ref_name }}' --repo '${{ github.repository }}' --notes ""
    - name: Upload plugin artifact to GitHub Release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release upload '${{ github.ref_name }}' ${{ inputs.output-directory }}/*.streamDeckPlugin \
        --repo '${{ github.repository }}'
